### PR TITLE
fix: refactor affiliate section

### LINKED ISSUE #85: Affiliation page - Step section
## Description 📹

Current one : https://starknet.id/affiliates/individual-program
image

New design :
image

Figma file : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=4211-4525&t=7vnPfugS15DehZEi-1

**Refactor this section with the new card structure, text, Lottie leaf animations, etc. Add a slide-in (bottom to top) or fade-in effect upon scrolling, if possible. It’s the same card of this issue : https://github.com/lfglabs-dev/starknet.id/issues/77**

[Falling leaf.json](https://github.com/user-attachments/files/18171558/Falling.leaf.json)

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by PedroCo3lho**
I used the PR #77 as reference

Ready for review @Marchand-Nicolas 

close #85

### CODE REVIEW

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Hello, it looks really good, well done! I appreciate the fact you based your PR on another similar one!
image
Can you remove these two small leaves in the center of the screen please ?

Screenshot 2025-02-13 at 1 58 36 PM
The quality for the card's image is a bit poor. Can you download 4x quality on figma please ?

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image

The images are not positioned exactly like on figma. They should touch the borders

**Comment by PedroCo3lho** [comment]
Hey @Marchand-Nicolas, requested changes addressed. Let me know if there's something else to fix

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
image
Contrarily to the landing page (which you reused the component), there shouldn't be ther numbers. Imo you can add a prop to the component to conditionaly display them. So that on the landing page they are there, but not on the affiliate page

**Comment by Marchand-Nicolas** [comment]
Please fix the git conflicts too @PedroCo3lho

**Comment by Marchand-Nicolas** [comment]
After that we're good :)

**Comment by PedroCo3lho** [comment]
Done boss @Marchand-Nicolas

File: components/affiliates/affiliateSection2.tsx [hunk 1]
```diff
@@ -1,37 +1,103 @@
...
+      title: "Get paid in Crypto (ETH & STRK in the future)",
+      description:
+        "We share revenue fairly. Every eligible sale made earns you at least 30% commissions. And this is just the start because you could go bigger if you are a top performer.",
+    },
+  ];
 
-const AffiliateSection2: FunctionComponent = () => {
   return (
     <div className={homeStyles.section2}>
-      <IntegratedBySection />
```
Comment (Marchand-Nicolas) [inline components/affiliates/affiliateSection2.tsx:10]: Please don't delete the integratedBySection

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
I think you deleted other contrib work while merging

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect, lgtm!
