### PR TITLE
Fix: Feedback footer - Fix the 'Newsletter' Link Redirect

### LINKED ISSUE #124: Feedback footer - Fixing the 'Newsletter' Link Redirect
## Description 📹

Image

**This link 'Newsletter' does not redirect to the correct location. Here is the correct link to use: https://app.starknet.id/newsletter**

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by dinahmaccodes**
This link 'Newsletter' does not redirect to the correct location. Here is the correct link to use: https://app.starknet.id/newsletter

close: #124

### CODE REVIEW

File: components/footer.tsx [hunk 1]
```diff
@@ -66,7 +66,7 @@ export default function Footer() {
                     PFP Collections
                   </Link>
                   <Link
-                    href="/"
+                    href="https://app.starknet.id/newsletter"
```
Comment (Marchand-Nicolas) [inline components/footer.tsx:69]: Please open in a new tab:
```html
target="_blank"
rel="noopener noreferrer"
```

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

File: components/footer.tsx (hunk 1 above)
Comment (dinahmaccodes) [reply components/footer.tsx:69]: alright. I'll do that

**Comment by dinahmaccodes** [comment]
Change made to open in new tab 

Close #issue124

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect! Lgtm
