### PR TITLE
Fix: the choose your domain button href link to sepolia testnet link

### LINKED ISSUE #62: Testnet landing page "Choose your domain" button redirects to mainnet instead of testnet
**Describe the bug**

The testnet landing page of Starknet Id `https://sepolia.starknet.id/` "Choose your button" button redirects to mainnet (`app.starknet.id`) instead of testnet (`sepolia.app.starknet.id`)

### PR DESCRIPTION
**Pull request by hemantwasthere**
Fixes #62

### CODE REVIEW

File: components/home/homeSection1.tsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ const HomeSection1: FunctionComponent = () => {
         subtitle="Create your Starknet Profile by claiming your stark domain and start using it everywhere in the ecosystem."
         mobileSubtitle="Step into the future with StarkNet ID. Begin by claiming your free StarkNet identity, your passport to the blockchain world. Register your unique .stark domain to transform your presence—say goodbye to the complex addresses. Elevate your StarkNet experience today."
         buttonName="Choose your domain"
-        buttonLink="https://app.starknet.id/"
+        buttonLink="https://sepolia.app.starknet.id/"
```
Comment (fricoben) [inline components/home/homeSection1.tsx]: You need to make it dynamic based on wich network the user is on

**Review by fricoben — CHANGES_REQUESTED** [review]
One comment

File: components/home/homeSection1.tsx (hunk 1 above)
Comment (hemantwasthere) [reply components/home/homeSection1.tsx]: okay will do it!

Comment (hemantwasthere) [reply components/home/homeSection1.tsx]: Done! As it's just a simple landing page there is no wallet connection to get the chain id, I updated the `buttonLink` according the origin url.

File: components/home/homeSection1.tsx [hunk 2]
```diff
@@ -12,7 +12,11 @@ const HomeSection1: FunctionComponent = () => {
         subtitle="Create your Starknet Profile by claiming your stark domain and start using it everywhere in the ecosystem."
         mobileSubtitle="Step into the future with StarkNet ID. Begin by claiming your free StarkNet identity, your passport to the blockchain world. Register your unique .stark domain to transform your presence—say goodbye to the complex addresses. Elevate your StarkNet experience today."
         buttonName="Choose your domain"
-        buttonLink="https://app.starknet.id/"
+        buttonLink={
+          window.location.origin.includes("sepolia")
+            ? "https://sepolia.app.starknet.id/"
+            : "https://app.starknet.id/"
```
Comment (fricoben) [inline components/home/homeSection1.tsx:20]: no you need to use the `env` variable we use to define if the user is on testnet or mainnet

**Review by fricoben — CHANGES_REQUESTED** [review]
Use the env variable `NEXT_PUBLIC_IS_TESTNET="true"`

File: components/home/homeSection1.tsx (hunk 2 above)
Comment (hemantwasthere) [reply components/home/homeSection1.tsx:20]: Done! please have a look once.

Comment (fricoben) [reply components/home/homeSection1.tsx:20]: It doesn't work because we have `"true"` not `true` :) 

So you have to do:
```ts
  const isTestnet = Boolean(process.env.NEXT_PUBLIC_IS_TESTNET === "true");
```

**Review by fricoben — CHANGES_REQUESTED** [review]

**Comment by hemantwasthere** [comment]
Done ser!

**Review by fricoben — APPROVED** [review]
lgtm

**Comment by hemantwasthere** [comment]
Hello @fricoben ser can you merge it, if everything seems fine

**Review by fricoben — APPROVED** [review]
lgtm
