### PR TITLE
Fix: Feedback Landing page

### LINKED ISSUE #101: Feedback Landing
## Description 📹

**1 - The proportion of the header image is too small. I think we can enlarge it to 500x500px. Also, the two small leaves around the image are missing. Here's the correct file to use :  [Header image.png.zip](https://github.com/user-attachments/files/18572054/Header.image.png.zip)**

Current : 
Image

New design :
Image

Figma file : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=4040-8018&t=Z7UwxvO5x57HzGQx-1

**2 - The leaves used are static, poorly positioned on the page (they should be in the Starknet Identity section), and they are not the animated Lottie files. They need to be correctly positioned in the right section, and the Lotties should be used: [Falling leaf.json](https://github.com/user-attachments/files/18171558/Falling.leaf.json)
**
Current : 
Image
Image

New design :
Image

Figma file : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=4040-8018&t=Z7UwxvO5x57HzGQx-1

**3 - The logos are much too small because I think there are too many visible. They need to be enlarged, like in the design.
**

Current : 
Image

New design :
Image

Figma file : https://www.figma.com/design/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?node-id=4040-8018&t=Z7UwxvO5x57HzGQx-1

## Proposed Actions 🛠️

Here’s a checklist of actions to follow for resolving this issue:

1. **Fork and Create Branch**:  
   Fork the repository and create a new branch using the issue number:
   ```bash
   git checkout -b fix-[issue-number]
   ```

2. **Implement Changes**:  
	[Insert Code snippet if needed with a mardown todo list]

3. **Run Tests and Commit Changes**:  
   Make sure your changes don't break existing functionality and commit with a clear message:
   ```bash
   git commit -m "Fix: [Short description of the fix]"
   ```

## Required 📋

To keep our workflow smooth, please make sure you follow these guidelines:

- **Assignment**: Don't create a pull request if you weren’t assigned to this issue.
- **Timeframe**: Complete the task within **3 business days**.
- **Closing the Issue**: In your PR description, close the issue by writing `Close #[issue_id]`.
- **Review Process**:
  - Once you've submitted your PR, change the label to **"ready for review"**.
  - If changes are requested, address them and then update the label back to **"ready for review"** once done.
- **Testing**: Test your PR locally before pushing, and verify that tests and build are working after pushing.

Thank you for your contribution 🙏

⚠️ WARNING: Failure to follow the requirements above may result in being added to the OnlyDust blacklist, affecting your ability to receive future rewards.

### PR DESCRIPTION
**Pull request by Benjtalkshow**
Closes #101 
For the task 1 "Changing the size of the header banner", i used 700 x 700 because i noticed that 500x500 was still small.

### CODE REVIEW

File: components/home/headerBanner.tsx [hunk 1]
```diff
@@ -5,8 +5,10 @@ const HeaderBanner: FunctionComponent = () => {
   return (
     <img
       alt="Header banner"
-      src="/visuals/home/headerBanner.webp"
+      src="/visuals/home/headerImage.png"
```
Comment (Marchand-Nicolas) [inline components/home/headerBanner.tsx]: Please use png format, not webp.
In addition, the image doesn't load, please test your code
image

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

File: components/home/headerBanner.tsx (hunk 1 above)
Comment (Benjtalkshow) [reply components/home/headerBanner.tsx]: @Marchand-Nicolas 
Do you mean i should use webp format instead of png? Because what i used is png format.
Additionally, i am wondering why the image is not loading from your end because it loads properly from my localhost and i tested it properly before pushing.

Comment (Marchand-Nicolas) [reply components/home/headerBanner.tsx]: @Benjtalkshow 
Yes, you should use webp, not png, sorry, just saw I inverted in my comment! 
For the image that doesn't load in production but loads in local, there can be two options:
- Either one letter should/shouldn't be uppercase in the image path. From my experience, the links are only case sensitive in production.
- Or, you use the CDNImg component. If so, you can replace it by the Image component from next/image

Comment (Benjtalkshow) [reply components/home/headerBanner.tsx]: @Marchand-Nicolas ,
I have fixed the headerBanner. But i noticed argent wallet, starkscan and braavos icons arent displaying too.

Comment (Marchand-Nicolas) [reply components/home/headerBanner.tsx]: > @Marchand-Nicolas , I have fixed the headerBanner. But i noticed argent wallet, starkscan and braavos icons arent displaying too.

Ah, where do you see t-it ? Can you send me a screenshot please @Benjtalkshow

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]
Too much space around the header image on mobile. Please use the same margins as on figma
Screenshot 2025-01-30 at 8 43 16 AM

Same here, there is too much space on mobile
Screenshot 2025-01-30 at 8 46 22 AM

File: components/home/headerBanner.tsx [hunk 2]
```diff
@@ -5,8 +5,10 @@ const HeaderBanner: FunctionComponent = () => {
   return (
     <img
       alt="Header banner"
-      src="/visuals/home/headerBanner.webp"
```
Comment (Marchand-Nicolas) [inline components/home/headerBanner.tsx:8]: If you add a new headerImage.webp file, then delete the headerBanner.webp file as it's not used anymore

**Review by Marchand-Nicolas — CHANGES_REQUESTED** [review]

**Comment by Benjtalkshow** [comment]
@Marchand-Nicolas 
Did the logo images load from your end?

**Comment by Marchand-Nicolas** [comment]
> @Marchand-Nicolas Did the logo images load from your end?

https://github.com/lfglabs-dev/starknet.id/pull/104#discussion_r1935145439

File: components/home/headerBanner.tsx (hunk 1 above)
Comment (Benjtalkshow) [reply components/home/headerBanner.tsx]: @Marchand-Nicolas 

[Watch Video](https://www.loom.com/share/5f109343cf6d4fb1ae6c9cf6901ceecd?sid=da00bdd7-6e7a-4cc1-9b36-2b1c34360b6c)

**Comment by Marchand-Nicolas** [comment]
Hello @Benjtalkshow I think it loads in production and not locally because the files doesn't exist (with that exact names), but the contributor used the CDNImg component, which makes it working in prod (because it uses the cached assets).
Can you replace it with the Image component (from next/image) please ? I guess you'll have to fix some links too, but at least by using this component I will have the same rendering as you

**Comment by Benjtalkshow** [comment]
> Hello @Benjtalkshow I think it loads in production and not locally because the files doesn't exist (with that exact names), but the contributor used the CDNImg component, which makes it working in prod (because it uses the cached assets). Can you replace it with the Image component (from next/image) please ? I guess you'll have to fix some links too, but at least by using this component I will have the same rendering as you

Alright sir.

**Comment by Benjtalkshow** [comment]
@Marchand-Nicolas 
I have fixed the large spaces on mobile.
Additionally, i use the `next/Image` as requested for the partners logos

**Review by Marchand-Nicolas — APPROVED** [review]
Perfect lgtm!
